### ISSUE TITLE
[Non-Issue] Great job!

### ISSUE THREAD

**Issue by RevanthRameshkumar** [mcclown/AquaIPy#10]
Great job on this! I was debating which lighting to buy and now I'm hands down going for AI.
I'll be sure to contribute to this as I use it in my automation w/ rasp. pi

**Comment by mcclown** [comment]
Thanks mate! AI have recently released an update to their range of devices. I haven't gotten my hands on any of them yet but I'm pretty hopeful that they'll work with this or at least will, with a little effort. Let me know if you get one of the new models and we can work together, if it doesn't just work out of the box.
